BEGIN TRANSACTION;
CREATE TABLE "android_metadata" ("locale" TEXT DEFAULT 'en_US');
INSERT INTO android_metadata VALUES('en_US');
CREATE TABLE evenement (nom TEXT, Lieu TEXT, Date_debut TEXT, Date_fin TEXT, _id INTEGER PRIMARY KEY, description TEXT, id_createur , heure TEXT);
INSERT INTO evenement VALUES('Cinéclub - "Old Boy"','Gd Amphi','28/01/12','28/01/12',1,'Projection de "Old Boy" par le ciné club , venez nombreux!',1,'20h30');
INSERT INTO evenement VALUES('Cinéclub - "Le Bon , La Brute et le Cinglé"','Gd Amphi','29/01/12','29/01/12',2,'Projection de "Le bon, la brute et le cinglé" par le ciné club , venez nombreux',1,'20h30');
INSERT INTO evenement VALUES('Art live - Diner Jazz','centre vie','02/02/12','02/02/12',3,'Ouverture du art live avec un Diner Jazz',5,'20h30');
INSERT INTO evenement VALUES('Before au I2','Cuisine I2','04/02/12','04/02/12',4,'Tout est dans le titre , venez prendre l''apéro samedi soir à la cuisine du I2',2,'21h');
INSERT INTO evenement VALUES('Sortie crêpes-ciné','Brest','18/02/12','18/02/12',5,'J''ai pensé qu''on pourrais se faire une crêperie à brest et aller voir J Edgar au ciné , rdv 18h30 sur le parking de telecom',3,'18h30');
INSERT INTO evenement VALUES('Cinéclub - "Les petits mouchoirs"','Gd Amphi','17/02/12','17/02/12',6,'Projection de "Les petits mouchoirs" , venez nombreux! ',1,'20h30');
CREATE TABLE participant (_id INTEGER PRIMARY KEY, nom TEXT, mail TEXT);
INSERT INTO participant VALUES(1,'Gaetan Fayon','gaetan.fayon@telecom-bretagne.eu');
INSERT INTO participant VALUES(2,'Nico','nicolas.retiere@telecom-bretagne.eu');
INSERT INTO participant VALUES(3,'Geoffroy CLAUSS','geoffroy.clauss@telecom-bretagne.eu');
INSERT INTO participant VALUES(4,'Abdel AGADAZI','aa.agadazi@telecom-bretagne.eu');
INSERT INTO participant VALUES(5,'le BDA','bda@telecom-bretagne.eu');
INSERT INTO participant VALUES(6,'Benoit Faure','benoit.faure@telecom-bretagne.eu');
INSERT INTO participant VALUES(7,'Martin Rebert','martin.rebert@telecom-bretagne.eu');
INSERT INTO participant VALUES(8,'Romain Fage','romain.fage@telecom-bretagne.eu');
INSERT INTO participant VALUES(9,'Guillaume Villette','guillaume.villette@telecom-bretagne.eu');
INSERT INTO participant VALUES(10,NULL,NULL);
INSERT INTO participant VALUES(11,NULL,NULL);
COMMIT;
